### PR TITLE
New axesservices

### PR DESCRIPTION
**Pull request by CoLa5**
Questions regarding naming:  

*Should we add `Rotational` to all RPC-names?*  

`GetRotationalPosition`  
`GetRotationalPositionLimits`  
`MoveToRotationalPosition`  

`GetRotationalVectorAccelerationLimit`  
`MoveToRotationalPositionWithRotationalVectorAcceleration`

### CODE REVIEW

**Comment by Smokrow** [comment]
@ax-meyer pulling you into this one. I would say so. Would make the statement quite obvious for the user

**Comment by CoLa5** [comment]
Then I change also this naming

**Comment by ax-meyer** [comment]
I would agree. Self-explaining code is the way to go.

**Comment by CoLa5** [comment]
More naming customization desired?

**Comment by Smokrow** [comment]
In that case we should add linear as well right?

**Comment by CoLa5** [comment]
Following normal speech: position/velocity/acceleration implies linear move -> so actually not
To distinguish it clearly from the rotational -> yes

**Comment by ax-meyer** [comment]
Seems all done to me or is there any further discussion preventing the merge?

**Comment by Smokrow** [comment]
Looks good to me. Merging in. @CoLa5 thank you. Really great work.

**Pull request merged**
