### PR TITLE
Proposal for mask to allow movement of just one axis.

### PR DESCRIPTION
**Pull request by ax-meyer**
Simple idea:

Add a mask field for coordinate arrays. Example shown for the simple rotational movement.

This allows to indicate which axes / dimensions should be moved. Otherwise, to move just one axis, I need to get the current position, change one value, send all coordinates back, which effectively doubles the number of requests.

I propose to add this as a general feature for repeated coordinates. If everyone agrees, I volunteer to go over all proto files and insert the field to all coordinate arrays.

### CODE REVIEW

**Comment by ax-meyer** [comment]
And I somehow can't mention @CoLa5 here. Can anyone of you mention him?

Edit: seemed to work even though autocomplete didn't show him.

**Comment by CoLa5** [comment]
First, I would say, we should distinguish two cases:  

**Case 1**: One axis controller and all axes are connected to each other, e.g. an Aerotech 3D table, where the x-axis sits on top of the y-axis, which sits on top of the z-axis, i.e. all axes depend on each other.
**Case 2**: One axis controller and the axes are independent of each other, e.g. the *Eigenbau*, where we are moving mirrors: The axis 1 moves one mirror, the axis 2 moves totally independent of axis 1 another mirror, but both axes are connected to one controller.  

In **Case 1**, I'm opposed to your proposal, since I cannot really move the axes independently of each other, since moving only the x-axis implies that the client knows exactly, where the y-axis and z-axis are at this moment. So for me, it's more explicit to require the full coordinate set and when you as a client need such a service, you can realize this with the `GetPosition` and `MoveToPosition`-combination, as you have mentioned. And since we are sending coordinates (e.g. 3*64bit floats), the size is a less significant drawback than being explicit, in my opinion.  

In **Case 2**, I'm in favor of your proposal, since the axes are *really* independent, but need to be controlled by a single service. But I would implement it differently to be clear:
```
message RotationalPosition {
  repeated RotationalCoordinate = 1;
}

message RorationalCoordinate {
  int rotational_axis_id = 1;
  double rotational_coordinates_in_rad = 2;
}
```

@Smokrow, what is your opinion?

**Comment by ax-meyer** [comment]
For case 1: I don't really see a benefit from doing it this way, even in this case. 

Any slightly general purpose client will implement a low level abstraction around this because a user at a machine expects to have arrow buttons to move an axis around. 

So neither during the user during usage or the developer during client implementation will explicitly think about the full set of coordinates every time. 

Usually, a machine software implementation will go even further and implement their own workpiece coordinate systems on top of this since users don't want to deal with raw axis coordinates because they are usually pretty meaningless in the application context. 

Having this client side abstraction just creates unnecessary boilerplate code and increases the amount of requests and the latency - which might actually be noticeable when we think of a full additional roundtrip for possibly every axis command once there are multiple additional service layers and a webstack on top of the hardware service.

For case 2: might be a solution, but I would not fragment the service for this, this would add even more complexity than the client side abstraction.

**Comment by CoLa5** [comment]
# Desing : Stateless? Multiple clients to one service?

> Any slightly general purpose client will implement a low level abstraction around this because a user at a machine expects to have arrow buttons to move an axis around.```

That is true, but at a low level, the amount of requests is still negligable.

> [...] increases the amount of requests and the latency - which might actually be noticeable when we think of a full additional roundtrip for possibly every axis command once there are multiple additional service layers and a webstack on top of the hardware service.

I think the major point is, in what use cases do we think:  

Will we always have one vs. one connection, where I can guarantee that no other client changed the z-coordinate while I'm just moving the x-coordinate? That's your example and in this case, with the current API I have to ask one time, in the beginning, the position, and then I can keep track of the position on the client-side, because every "move only x-axis"-call implies the knowledge of knowing the position of the other axes.

Or will we have multiple clients, which interact more or less simultaneously with the service? So I cannot guarantee e.g. that the z-coordinate stays the same while I'm calling multiple move commands on my x-axis because in the meantime another client did change it.
That's why I think we decided up to now always for the whole coordinate set because I'll never know what happened in between my RPC calls. At least it guarantees to have the axes where we expect it to be directly after the RPC call.
And it forces the user to define the whole coordinate set, which avoids errors in the case that I'm using two clients simultaneously which use e.g. a different height.

Even though, it does not really solve the problem, since we are running into the problem of having multiple clients calling one service, which is pretty unique in the microservice area I think. So actually we need to block the axes for a certain number of RPC calls that depend on each other or for a certain "time" where the axes must stay at a position. This at the same time would definitely introduce a state into our service. But the solution to this is a whole new task.

> Usually, a machine software implementation will go even further and implement their own workpiece coordinate systems on top of this since users don't want to deal with raw axis coordinates because they are usually pretty meaningless in the application context.

That is also true, but our plan up to now has been to keep the axes service as **simple as possible** and implement this kind of stuff at a higher microservice level / on the client-side:  
The basic axes service should be enabled and homed one time in the beginning and it has one global coordinate system and every move command is issued in regard to this coordinate system. This should make it "stateless" in the kind, that the same move commands lead always to the same result, which cannot be guaranteed if we introduce different coordinate systems. Furthermore, I could imagine having multiple workpieces over my service lifetime, which should be handled also on the client-side, because I don't want to restart my service for this. Of course, it would be possible to write a gRPC-API for it, but with highly increasing complexity.

# Design

> For case 2: might be a solution, but I would not fragment the service for this, this would add even more complexity than the client-side abstraction.

```
message RotationalPosition {
  repeated double rotational_coordinates_in_rad = 1;

  // mask to indicate which values are valid / should be used.
  // especially usefull to just move one axis / dimension
  repeated bool mask = 2;
}
```

For me, the major drawback is the lacking clarity of the interface:
Does `rotational_coordinates_in_rad = [10, 0];  mask=[False, True]` mean to just change the second axis, although the first one is not zero and although old service versions, which do not care about the mask, would still move both axes!?
Or do u want to implement it in the way that `rotational_coordinates_in_rad = [10];  mask=[False, True, False]` means a change of the second axis position to `10 rad`?

I think the clearest version would be to use a map:
```
message RotationalPosition {
  map<int, double> rotational_coordinate_in_rad = 1;
}
```
where `int`-key would be the axis ID and works pretty much as a python dictionary. At the same time, this breaks the old version and throws an error when we have a new client - old service combination or the other way around.

**Comment by ax-meyer** [comment]
Pulling this part up because its the one leading me to agree with you on its own already:
> # Design
> > For case 2: might be a solution, but I would not fragment the service for this, this would add even more complexity than the client-side abstraction.
> 
> ```
> message RotationalPosition {
>   repeated double rotational_coordinates_in_rad = 1;
> 
>   // mask to indicate which values are valid / should be used.
>   // especially usefull to just move one axis / dimension
>   repeated bool mask = 2;
> }
> ```
> 
> For me, the major drawback is the lacking clarity of the interface:
> Does `rotational_coordinates_in_rad = [10, 0]; mask=[False, True]` mean to just change the second axis, although the first one is not zero and although old service versions, which do not care about the mask, would still move both axes!?
> Or do u want to implement it in the way that `rotational_coordinates_in_rad = [10]; mask=[False, True, False]` means a change of the second axis position to `10 rad`?

I don't think the clarity would be an issue for the first thing. Using some kind of value + mask interface is common in hardware control (e.g. setting IOs on scanlab and newson scanners works like this). 

I agree that it is bad in terms of backward compatibility for our services here, this woul lead to unexpected behavior.
And that's what kills it for me at the moment. To make this work, we would have to introdcue a breaking change, and thats definitely not worth it. Maybe we can think about it again if we ever do a breaking redesign for the API.

---
Still some comments / clarifications for the other stuff, just for completeness:

> # Desing : Stateless? Multiple clients to one service?
> > Any slightly general purpose client will implement a low level abstraction around this because a user at a machine expects to have arrow buttons to move an axis around.```
> 
> That is true, but at a low level, the amount of requests is still negligable.
> 
> > [...] increases the amount of requests and the latency - which might actually be noticeable when we think of a full additional roundtrip for possibly every axis command once there are multiple additional service layers and a webstack on top of the hardware service.

True, I didn't really think the whole stack through with the latency argument.

> I think the major point is, in what use cases do we think:
> 
> Will we always have one vs. one connection, where I can guarantee that no other client changed the z-coordinate while I'm just moving the x-coordinate? That's your example and in this case, with the current API I have to ask one time, in the beginning, the position, and then I can keep track of the position on the client-side, because every "move only x-axis"-call implies the knowledge of knowing the position of the other axes.
> 
> Or will we have multiple clients, which interact more or less simultaneously with the service? So I cannot guarantee e.g. that the z-coordinate stays the same while I'm calling multiple move commands on my x-axis because in the meantime another client did change it.
> That's why I think we decided up to now always for the whole coordinate set because I'll never know what happened in between my RPC calls. At least it guarantees to have the axes where we expect it to be directly after the RPC call.
> And it forces the user to define the whole coordinate set, which avoids errors in the case that I'm using two clients simultaneously which use e.g. a different height.
> 
> Even though, it does not really solve the problem, since we are running into the problem of having multiple clients calling one service, which is pretty unique in the microservice area I think. So actually we need to block the axes for a certain number of RPC calls that depend on each other or for a certain "time" where the axes must stay at a position. This at the same time would definitely introduce a state into our service. But the solution to this is a whole new task.

This is a whole new task, yes. Having multiple services just moving the axis around is not really feasible. E.g. client 1 moves the axis to a certain position and wants to execute a scan job, and some other service just moves it away again?

I would think however that it is the job of the developer of the client software to make sure that his software has proper flow control in this regard and that the measurement service does not just decide to move the axis around while the scanservice is working on a job.

> 
> > Usually, a machine software implementation will go even further and implement their own workpiece coordinate systems on top of this since users don't want to deal with raw axis coordinates because they are usually pretty meaningless in the application context.
> 
> That is also true, but our plan up to now has been to keep the axes service as **simple as possible** and implement this kind of stuff at a higher microservice level / on the client-side:
> The basic axes service should be enabled and homed one time in the beginning and it has one global coordinate system and every move command is issued in regard to this coordinate system. This should make it "stateless" in the kind, that the same move commands lead always to the same result, which cannot be guaranteed if we introduce different coordinate systems. Furthermore, I could imagine having multiple workpieces over my service lifetime, which should be handled also on the client-side, because I don't want to restart my service for this. Of course, it would be possible to write a gRPC-API for it, but with highly increasing complexity.

I agree, maybe it was written a bit confusing by me. Additional coordinate systems should be implemented on top of this service, not in this service. I think we might think about implementing a (stateful) workpiece coordinate service which then utilizes the axesservice so that clients have easy access to workpiece coordinates.

**Pull request closed without merging**
